import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="relative bg-black">
          <div className="absolute top-0 left-0 w-full h-full">
            <img
              className="h-screen w-full object-cover"
              src="./green-fake-grass-background-4k.jpg"
              alt="Image by rawpixel.com on Freepik (https://www.freepik.com/free-photo/green-fake-grass-background_2791853.htm#query=football%20background&position=13&from_view=keyword&track=ais&uuid=4899e273-bbf2-4a83-bb6a-11e42676c552)"
            />
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
